config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # root to: 'pages#team'
  get "/pages/:page" => "pages#show"
  get "/pages/team" => "pages#team"
  resources :trips do
    resources :activity_bookings, only: [:index, :new, :create, :update, :edit, :show ]
    resources :hotel_bookings, only: [:index, :new, :create, :update, :edit, :show ]
  end
  resources :activity_bookings, only: [ :destroy ]
  resources :hotel_bookings, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :trip_reviews
  has_many :user_invitations
  has_many :hotel_bookings
  has_many :activity_bookings
  has_many :activities, through: :activity_bookings, dependent: :destroy
  has_many :hotels, through: :hotel_bookings, dependent: :destroy

  geocoded_by :destination
  after_validation :geocode, if: :will_save_change_to_destination?
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    # @trips = policy_scope(Trip)
    @trips = Trip.all

    # @trips = policy_scope(Trip).order(created_at: :desc)
    @markers = @trips.geocoded.map do |trip|
      {
        lat: trip.latitude,
        lng: trip.longitude,
        info_window: render_to_string(partial: "info_window_trip", locals: {
          trip: trip }),
          image_url: helpers.asset_url('icons/pin.png')
        }
      end
      @trips = @trips.sort_by { |trip|[trip.date_coming] }
  end

    # if params[:query].present?
    #   @trips = Trip.where(destination: params[:query])
    # else
    #   @trips = Trip.all
    # end

    # if params[:query].present?
    #   @trips = Trip.where("destination ILIKE ?", "%#{params[:query]}%")
    # else
    #   @trips = Trip.all
    # end

    # @markers = @trips.geocoded.map do |trip|
    #   {
    #     lat: trip.latitude,
    #     lng: trip.longitude,
    #     info_window: render_to_string(partial: "info_window", locals: { trip: trip })
    #   }
    # end

  def show
    @trip = Trip.find(params[:id])
    @activity_bookings = @trip.activity_bookings.sort_by { |trip|[trip.booking_date] }
    # @trip.activity_bookings.booking_dates.sort
    # @trip.activity_bookings.sort_by { |trip| [trip.booking_date] }
    # sorted_date = @trip.activity_bookings
    # sorted = @trip.activity_bookings.booking_date.sort
    # sorted.reverse! if direction == "DESC"

    count_price = 0
    final_price = 0
    @trip.activity_bookings.each do |activity_booking|
      if activity_booking.activity.price.nil?
        puts "No fixed price for an activity"
      else
        count_price += 1
        final_price += activity_booking.activity.price * activity_booking.people
      end
    end
    @trip.total_price = final_price


    @hotel_booking = @trip.hotel_bookings.first
    # dates_array = (@trip.date_coming.strftime("%b %d, %Y").to_date..@trip.date_leaving.strftime("%b %d, %Y").to_date).map {|d| d }
    unless @hotel_booking.nil?
      dates_array = (@hotel_booking.date_coming.strftime("%b %d, %Y").to_date..@hotel_booking.date_leaving.strftime("%b %d, %Y").to_date).map {|d| d }
    end

    # dates_index = dates_array.index
    @trip.hotels.each do |hotel|
      if hotel.price.nil?
        puts "No Price for the Hotel yet"
      else
        final_hotel = hotel.price * (dates_array.count - 1)
      end
      @trip.total_price = final_price + final_hotel
    end

    markers_hotels = @trip.hotels.geocoded.map do |hotel|
      {
        lat: hotel.latitude,
        lng: hotel.longitude,
        info_window: render_to_string(partial: "info_window_hotel", locals: {
        hotel: hotel }),
        image_url: helpers.asset_url('icons/hotel.png')
      }
    end
    markers_activities = @trip.activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "info_window_activity", locals: {
        activity: activity }),
        image_url: helpers.asset_url('icons/restaurant.png')
      }
    end
    @markers = markers_hotels.concat markers_activities
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip), notice: 'New Trip was created successfully!'
    else
      render :new
    end
  end

  # def destroy
  #   @trips = Trip.find(params[:id])
  #   @trips.destroy
  #   redirect_to trips_path
  # end
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    redirect_to trips_path
  end


  private

  def trip_params
    params.require(:trip).permit(:type_transportation, :destination, :date_leaving, :date_coming, :booked, :total_price, :people, :user_id)
  end
end

app/views/trips/_info_window_activity.html.erb
<div>
  <%=link_to activity.name, trip_activity_booking_path(@trip, activity), class: "btn btn-hotel_show", id: "button-hotel_show" %>
</div>
<br>
<div>
  <i class="fas fa-map-marker"></i>
  <p> <%= activity.address %></p>
</div>
  <i class="fas fa-info-circle"></i>
  <p> <%= activity.category %></p>
<div>

app/views/trips/_info_window_hotel.html.erb
<div>
  <%=link_to hotel.name, trip_hotel_booking_path(@trip, hotel), class: "btn btn-hotel_show", id:"button-hotel_show"%>
</div>
<br>
<div>
  <i class="fas fa-map-marker"></i>
  <p class="address"> <%= hotel.address %></p>
</div>
<div>
  <i class="fas fa-info-circle"></i>
  <p class="description"> $<%= hotel.price %></p>
</div>

app/views/trips/_info_window_trip.html.erb
<div>
  <%= link_to trip.destination, trip_path(trip), class: "btn btn-hotel_show", id:"button-hotel_show" %>
</div>
<br>
<p>Arrival date: <strong><%= trip.date_coming.strftime("%b %d, %Y") %></strong></p>
<p>Leaving date: <strong><%= trip.date_leaving.strftime("%b %d, %Y") %></strong></p>

app/views/trips/create.html.erb
<% @trips.each do |trip| %>
  <% if policy(trip).edit? %>
    <%= link_to "Update", edit_trip_path(trip) %>
  <% end %>
<% end %>

app/views/trips/index.html.erb
<%= render 'layouts/navbar' %>


<%# @trips.each do |trip|%>
  <%# <p>= link_to trip.destination, trip_path(trip)</p> %>
  <%# <p>Total Price:= trip.total_price</p> %>
  <%# <p>Arrival Date: = trip.date_coming</p> %>
  <%# <p>Leaving Date: = trip.date_leaving</p> %>
  <%# <p>= trip.type_transportation</p> %>
  <%# <p>Number of people: = trip.people</p> %>
  <%# <br>
  <br>
  <br>
  <br> %>
<%# end %>
<div class="justify-content-center" id="all-trips">
<% @trips.each do |trip|%>
  <div class="card-trips" id="a-t-c">
    <div class="row">
      <div class="col-lg-2" id="default-activity-icon_index_trip">
        <%= link_to trip_path(trip) do %>
          <i id="add-icon" class="fas fa-map-marker-alt" style="font-size:40px;"></i>
        <% end %>
      </div>

      <div class="col-lg-8" id="activity-info">
          <p id="default-card-content_index_trips">Your Trip to:</p>
          <%= link_to trip_path(trip) do %>
            <h3 id="default-card-content_index_trips"><%= trip.destination %></h3>
          <% end %>
          <p id="default-card-content_index_trips">Arrival date: <strong><%= trip.date_coming.strftime("%b %d, %Y") %></strong></p>
          <p id="default-card-content_index_trips">Leaving date: <strong><%= trip.date_leaving.strftime("%b %d, %Y") %></strong></p>
      </div>


      <div class="col-md-2" id="default-edit-icon">
        <%= link_to trip_path(trip), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i id="add-icon" class="far fa-trash-alt" style="font-size:40px;"></i>
        <% end %>
        <%# <i class="fas fa-file-contract" style="font-size:32px;"></i> %>
      </div>
    </div>
  </div>
<% end %>
</div>

<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/trips/new.html.erb
<div class="container mt-3 mb-5" data-controller="trips-form">
  <div class="d-flex mb-5" id="bar-1">
    <div class="bar-item col-lg-3 completed" id="destination-tab" data-trips-form-target="destinationTab">Destination</div>
    <div class="bar-item col-lg-3" id="timeframe-tab" data-trips-form-target="timeframeTab">Timeframe</div>
    <div class="bar-item col-lg-3" id="people-tab" data-trips-form-target="peopleTab">People</div>
    <div class="bar-item col-lg-3" id="transport-tab" data-trips-form-target="transportTab">Transport</div>
  </div>

  <%= form_for(@trip) do |t| %>
  <div class="form-group" data-trips-form-target="destination group">
    <div class="label text-center">
    <%= t.label :Which_destination_would_you_like_to_visit? %>
    </div>
    <div>
    <%= t.text_field :destination, class: 'form-control', placeholder: 'Hamburg' %>
    </div>
    <div class="buttons-below d-flex justify-content-between">
      <div class="text-left">
        <%= link_to "Go Back", root_path, class: "btn mt-5 text-center next", id:"button-left" %>
      </div>
      <div class="text-right">
        <div class="btn mt-5 text-center next" id="button-right" data-action="click->trips-form#revealTimeframe">Next</div>
      </div>
    </div>
  </div>
  <div class="form-group d-none" data-trips-form-target="timeframe group">
    <div class="label text-center">
    <%= t.label :What_is_the_timeframe_of_your_trip? %>
    </div>
    <div class="timeframe d-flex justify-content-between row">
    <%= t.date_field :date_coming, class: 'form-control col-lg-6', id: 'timeframe', placeholder: 'Check-in date' %>
    <%= t.date_field :date_leaving, class: 'form-control col-lg-6', id: 'timeframe', placeholder: 'Check-out date' %>
    </div>
    <div class="buttons-below d-flex justify-content-between">
    <div class="text-left">
    <div class="btn mt-5 text-center next" id="button-left" data-action="click->trips-form#previousDestination">Previous</div>
    </div>
    <div class="text-right">
    <div class="btn mt-5 text-center next" id="button-right" data-action="click->trips-form#revealPeople">Next</div>
    </div>
    </div>
  </div>
  <div class="form-group d-none" data-trips-form-target="people group">
    <div class="label text-center">
    <%= t.label :How_many_people_are_you? %>
    </div>
    <div>
    <%= t.number_field :people, class: 'form-control', min: 1 %>
    </div>
    <div class="buttons-below d-flex justify-content-between">
      <div class="text-left">
        <div class="btn mt-5 text-center next" id="button-left" data-action="click->trips-form#previousTimeframe">Previous</div>
      </div>
      <div class="text-right">
        <div class="btn mt-5 text-center next" id="button-right" data-action="click->trips-form#revealTransport">Next</div>
      </div>
    </div>
  </div>

  <div class="form-group d-none" data-trips-form-target="transport group">
    <div class="label text-center ">
     <%= t.label :Do_you_need_a_transport_recommendation? %>
    </div>
    <div>
      <%= t.select :type_transportation, User::TRANSPORTATION, {}, { class: 'select2, form-control' } %>
    </div>
    <div class="buttons-below d-flex justify-content-between">
      <div class="text-left">
        <div class="btn mt-5 text-center next" id="button-left" data-action="click->trips-form#previousPeople">Previous</div>
      </div>
      <div class="text-right mt-5">
        <button class="btn btn-primary", id="button-submit">Create your trip!</button>
      </div>
    </div>
  </div>
  </div>


<%end%>
</div>

app/views/trips/show.html.erb
<div class="show">
  <div id="left">
    <h3 id="filters">Notebook</h3>
    <div class="mt-5">
      <div>
        <div class="nav flex-column">
          <div class="nav-link completed">
            Overview
          </div>
            <% dates_array = (@trip.date_coming.strftime("%b %d, %Y").to_date..@trip.date_leaving.strftime("%b %d, %Y").to_date).map {|d| d } %>
              <% dates_array.each do |date_two| %>
                <div class="nav-link">
                  <a href="#<%= date_two.strftime("%d") %>" class="anti_link>"><%= date_two.strftime("%A, %b %d") %></a>
                </div>
              <% end %>
        </div>
      </div>
    </div>
  </div>
  <div id="middle">
    <div class="text-right">
        <%= link_to "Book your trip", trips_path, class: "btn btn-primary", id:"button-book" %>
    </div>
    <div id="destination">
      <h2 class="text-center">Your trip to <%= @trip.destination %></h2>
    </div>
    <div class="information d-flex justify-content-between pl-5 py-3">
      <div id="people-number d-flex">
        <i class="material-icons" style="font-size:32px;">group</i>
        <h5><%= @trip.people %></h5>
      </div>
      <div id="price d-flex">
        <h5 style="font-size:32px;">Total: $ <%= @trip.total_price %></h5>
      </div>
      <div id="transport d-flex">
        <i class="material-icons" style="font-size:32px;">hail</i>
        <h5><%= @trip.type_transportation %></h5>
      </div>
    </div>
      <% if @trip.hotel_bookings.empty? %>
      <div class="card" id="default-card">
       <div class="row">
          <div class="col-lg-2" id="default-activity-icon">
            <%= link_to trip_hotel_bookings_path(@trip) do %>
              <i id="add-icon" class="material-icons" style="font-size:60px;">add</i>
            <% end %>
          </div>
            <div class="col-lg-8" id="activity-infos">
              <p id="default-card-content">Let's get started!</p>
              <h3 id="default-card-content">Add an Accommodation</h3>
            </div>
          <div class="col-md-2" id="default-edit-icon">
            <i class="material-icons" style="font-size:32px;">hotel</i>
          </div>
        </div>
      </div>
      <% else %>
        <% end %>
      <% if @trip.activity_bookings.empty? %>
          <div class="card" id="default-card">
          <div class="row">
              <div class="col-lg-2" id="default-activity-icon">
                <%= link_to trip_activity_bookings_path(@trip) do %>
                  <i id="add-icon" class="material-icons" style="font-size:60px;">add</i>
                <% end %>
              </div>
              <div class="col-lg-8" id="activity-infos">
                  <p id="default-card-content">Let's get started!</p>
                  <h3 id="default-card-content">Add an Activity</h3>
              </div>
              <div class="col-md-2" id="default-edit-icon">
                <i class="material-icons" style="font-size:32px;">celebration</i>
              </div>
        </div>
        </div>
        <% else %>
        <div class="card" id="default-card">
          <div class="row">
            <div class="col-lg-2" id="default-activity-icon">
              <%= link_to trip_activity_bookings_path(@trip) do %>
              <i id="add-icon" class="material-icons" style="font-size:60px;">add</i>
              <% end %>
            </div>
            <div class="col-lg-8" id="activity-infos">
              <p id="default-card-content"></p>
              <h3 id="default-card-content">Add more Activities</h3>
            </div>
            <div class="col-md-2" id="default-edit-icon">
              <i class="material-icons" style="font-size:32px;">celebration</i>
            </div>
          </div>
        </div>
      <% end %>
<%# "%b %d, %Y" %>
      <% dates_array_two = (@trip.date_coming.strftime("%A, %b %d").to_date..@trip.date_leaving.strftime("%A, %b %d").to_date).map {|d| d } %>
        <% dates_array_two.each do |date_two| %>
        <%# raise %>
          <%#= date_two.strftime("%A, %b %d") %>
          <div class="card date_card">
          <div class='anchor' id="<%= date_two.strftime("%d") %>"></div>
            <div class="row">
              <div class="col-lg-2" id="default-activity-icons">
                <%#= link_to trip_activity_bookings_path(@trip) do %>
                  <%# <i id="fas fa-calendar-day" style="font-size:40px;"></i> %>
                <%# end %>
              </div>
              <div class="col-lg-8" id="activity-info">
                <%# <p id="default-card-content">Nothing added yet</p> %>
                <h3 id="default-card-content"><%= date_two.strftime("%A, %b %d") %></h3>
                </div>
                <div class="col-md-2" id="default-edit-icon">
                  <%# <i class="material-icons" style="font-size:32px;">celebration</i> %>
                </div>
              </div>
            </div>
            <%# raise %>
            <% if @trip.hotel_bookings.present? && @trip.hotel_bookings.first.date_coming.strftime("%A, %b %d") == date_two.strftime("%A, %b %d") %>
              <% @trip.hotel_bookings.each do |hotel|%>
                <div class="day-program">
                  <div class="d-flex justify-content-between">
                    <%# <h4>Check in: = hotel.date_coming.strftime("%A, %b %d")</h4> %>
                  </div>
                  <div class="card" id="hotel_card">
                    <div class="row">
                      <div class="col-lg-2" id="activity-icon">
                        <i class="fas fa-hotel" style="font-size:40px;"></i>
                      </div>
                      <div class="col-lg-8" id="activity-infos">
                        <%= link_to trip_hotel_booking_path(@trip, hotel) do %>
                          <p id="card-content"><%= hotel.hotel.address %></p>
                          <h3 id="card-content">Check in at: <%= hotel.hotel.name %></h3>
                        <% end %>
                      </div>
                      <div class="col-md-2" id="edit-icon">
                        <%= link_to edit_trip_hotel_booking_path(@trip, hotel) do %>
                          <i class="material-icons" id="edit-icon" style="font-size:32px;">edit</i>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
            <% @trip.activity_bookings.each do |activity|%>
              <% if activity.present? && activity.booking_date.strftime("%A, %b %d") == date_two.strftime("%A, %b %d")%>
                <div class="day-program">
                  <div class="day">
                  </div>
                  <div class="card" id="date_card_two">
                    <div class="row">
                      <% if activity.activity.category.include?('restaurant') %>
                        <div class="col-lg-2" id="activity-icon">
                          <i class="fas fa-concierge-bell" style="font-size:50px;"></i>
                        </div>
                      <% elsif activity.activity.category.include?('bar') %>
                        <div class="col-lg-2" id="activity-icon">
                          <i class="material-icons" style="font-size:50px;">local_bar</i>
                        </div>
                      <% elsif activity.activity.category.include?('museum') %>
                        <div class="col-lg-2" id="activity-icon">
                          <i class="fas fa-landmark" style="font-size:50px;"></i>
                        </div>
                      <% elsif activity.activity.category.include?('club') %>
                        <div class="col-lg-2" id="activity-icon">
                          <i class="fas fa-glass-cheers" style="font-size:50px;"></i>
                        </div>
                      <% end %>
                      <div class="col-lg-8" id="activity-infos">
                          <%= link_to trip_activity_booking_path(@trip, activity) do %>
                            <h6 id="card-content"><%= activity.booking_date.strftime("%b %e, %l:%M %p") %></h6>
                            <h3 id="card-content"><%= activity.activity.name %></h3>
                          <% end %>
                      </div>
                      <div class="col-md-2" id="edit-icon">
                        <%= link_to edit_trip_activity_booking_path(@trip, activity) do %>
                          <i class="material-icons" id="edit-icon" style="font-size:32px;">edit</i>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% elsif activity.present? == false%>
              <div class="card" id="default-card">
                <div class="row">
                  <div class="col-lg-2" id="default-activity-icon">
                <%#= link_to trip_activity_bookings_path(@trip) do %>
                  <%# <i id="fas fa-calendar-day" style="font-size:40px;"></i> %>
                <%# end %>
                  </div>
                  <div class="col-lg-8" id="activity-infos">
                <%# <p id="default-card-content">Nothing added yet</p> %>
                    <p id="default-card-content">No Activity added yet</p>
                  </div>
                  <div class="col-md-2" id="default-edit-icon">
                  <%# <i class="material-icons" style="font-size:32px;">celebration</i> %>
                  </div>
                </div>
              </div>
              <% end %>
            <% end %>
            <% if @trip.hotel_bookings.present? && @trip.hotel_bookings.first.date_leaving.strftime("%A, %b %d") == date_two.strftime("%A, %b %d") %>
              <% @trip.hotel_bookings.each do |hotel|%>
                <div class="day-program">
                  <div class="card" id="date_card_two">
                    <div class="row">
                      <div class="col-lg-2" id="activity-icon">
                        <i class="fas fa-hotel" style="font-size:40px;"></i>
                      </div>
                      <div class="col-lg-8" id="activity-infos">
                        <p id="card-content"><%= hotel.hotel.address %></p>
                        <h3 id="card-content">Check out at: <%= hotel.hotel.name %></h3>
                      </div>
                      <div class="col-md-2" id="edit-icon">
                        <i class="material-icons" style="font-size:32px;">edit</i>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
            <p id="unnecessary_center">___________________________________</p>
          <% end %>
    </div>
  <% if @trip.hotel_bookings.empty? && @trip.activity_bookings.empty? %>
    <div class="right" id="madrid"></div>
    <% else %>
    <div class="right" id="map"
      style="width: 100%; height: 750px;"
      data-markers="<%= @markers.to_json%>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <% end %>
</div>