config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # root to: 'pages#team'
  get "/pages/:page" => "pages#show"
  get "/pages/team" => "pages#team"
  resources :trips do
    resources :activity_bookings, only: [:index, :new, :create, :update, :edit, :show ]
    resources :hotel_bookings, only: [:index, :new, :create, :update, :edit, :show ]
  end
  resources :activity_bookings, only: [ :destroy ]
  resources :hotel_bookings, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hotel_booking.rb
class HotelBooking < ApplicationRecord
  belongs_to :trip
  belongs_to :hotel
end

app/controllers/hotel_bookings_controller.rb
class HotelBookingsController < ApplicationController
  def index
    @trip = Trip.find(params[:trip_id])
    # @hotels = Hotel.all
    if @trip.destination.present?
      @hotels = Hotel.where("city ILIKE ?", "%#{@trip.destination}%")
    # else
    #   @activities = Activity.all
    end
  end

  def show
    @hotel_booking = HotelBooking.find(params[:id])
  end

  def new
    @hotel_booking = HotelBooking.new
    @trip = Trip.find(params[:trip_id])
    @hotel_booking.trip = @trip
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @hotel_booking = HotelBooking.new(hotel_booking_params)
    @hotel_booking.trip = @trip
    if @hotel_booking.save!
      redirect_to trip_path(@trip), notice: 'New hotel Booking was created successfully!'
    else
      render :new
    end
  end

  def destroy
    @hotel_booking = HotelBooking.find(params[:id])
    @trip = @hotel_booking.trip
    @hotel_booking.destroy
    redirect_to trip_path(@trip)
  end

  def update
    @hotel_booking = HotelBooking.find(params[:id])
    @hotel_booking.update(hotel_booking_params)
    @trip = @hotel_booking.trip
    redirect_to trip_path(@trip)
  end

  def edit
    @hotel_booking = HotelBooking.find(params[:id])
    @trip = Trip.find(params[:trip_id])
    @hotel_booking.trip = @trip
  end

  private

  def hotel_booking_params
    params.require(:hotel_booking).permit(:date_coming, :date_leaving, :hotel_id)
  end
end

app/views/hotel_bookings/edit.html.erb
<%= simple_form_for([@trip, @hotel_booking]) do |f| %>
  <%= f.input :date_coming %>
  <%= f.input :date_leaving %>
  <%= f.association :hotel %>
  <%= f.button :submit %>
  <%= link_to "Delete Reservation" , hotel_booking_path(), method: :delete, data: { confirm: "Are you sure?" }%>
<%end%>

app/views/hotel_bookings/index.html.erb
<%# @hotels.each do |hotel|%>
  <%# if hotel.photo.attached? %>
    <%#= image_tag hotel.photo , height: 500, width: 700, crop: :fill %>
  <%# else %>
    <%# <h4>"No pictures"</h4> %>
  <%# end %>

<div class="activity-index-container">
<% @hotels.each do |hotel|%>
  <div class="body_activity_show">
    <div class="container_activity_show">
      <div class="card_activity_show">
        <div class="card-header_activity_show" style="background-image: url(<%= cl_image_path hotel.photo.key, height: 180, crop: :lfill %>)">
          </div>
        <div class="card-body_activity_show">
          <span class="tag_activity_show tag-teal_activity_show align-center">
            <%= link_to new_trip_hotel_booking_path(@trip, hotel_id: hotel.id) do %>
              <button class="btn btn-primary" id="button-home-3">Add this hotel</button>
            <% end %>
          </span>
          <br>
          <h4><%= hotel.name %></h4>
          <p><%= hotel.description %></p>
          <div class="user_activity_show">
            <div class="user-info_activity_show">
              <h5>Price Class: <%= hotel.price_class %>/4</h5>
              <br>
              <h5>$<%= hotel.price %> per Night</h5>
              <small><%= hotel.address %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/hotel_bookings/new.html.erb
<%= form_for([@trip, @hotel_booking]) do |t| %>
  <div class="d-none">
  <%= t.text_field :hotel_id, value: params[:hotel_id], as: :hidden%>
  </div>
  <div class="label text-center" id="ab-1">
    <%= t.label :For_which_days_do_you_need_an_accommodation? %>
  </div>
    <div class="timeframe d-flex justify-content-between row">
    <%= t.datetime_field :date_coming, class: 'form-control col-lg-6', id: 'timeframe', placeholder: 'Check-in date' %>
    <%= t.datetime_field :date_leaving, class: 'form-control col-lg-6', id: 'timeframe', placeholder: 'Check-out date' %>
    </div>
  <%# <%= f.association :hotel %>
    <div class="text-center">
      <%= t.button :submit, class: 'mt-5', id: 'button-home-3' %>
    </div>
<%end%>

app/views/hotel_bookings/show.html.erb
<div class="background-show d-flex justify-content-center">
  <div class="background_show_activity">
    <div class="background_show_activity_two">
      <div class="text-left">
        <%= link_to "BACK", trip_path(@hotel_booking.trip), class: "btn btn-primary", id:"button-left-2" %>
      </div>
      <%# <p><%= @activity_booking.trip</p> %>
      <h3 class="text-center"><%= @hotel_booking.hotel.name %></h3>
      <h4><b>Price Class</b></h4>
      <p><%= @hotel_booking.hotel.price_class %></p>
      <h4><b>Description</b></h4>
      <p><%= @hotel_booking.hotel.description %></p>
      <h4><b>Adress</b></h4>
      <p><%= @hotel_booking.hotel.address %></p>
      <h4><b>Price</b></h4>
      <p><%= @hotel_booking.hotel.price %></p>

      <h4><b>Booking Timreframe</b></h4>
      <p><%= @hotel_booking.date_coming.strftime("%A, %b %d") %> - <%= @hotel_booking.date_leaving.strftime("%A, %b %d") %></p>

    </div>
  </div>
</div>