config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # root to: 'pages#team'
  get "/pages/:page" => "pages#show"
  get "/pages/team" => "pages#team"
  resources :trips do
    resources :activity_bookings, only: [:index, :new, :create, :update, :edit, :show ]
    resources :hotel_bookings, only: [:index, :new, :create, :update, :edit, :show ]
  end
  resources :activity_bookings, only: [ :destroy ]
  resources :hotel_bookings, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity_booking.rb
class ActivityBooking < ApplicationRecord
  belongs_to :trip
  belongs_to :activity
end

app/controllers/activity_bookings_controller.rb
class ActivityBookingsController < ApplicationController
  def index
    @trip = Trip.find(params[:trip_id])
    # @activities = Activity.all
    if @trip.destination.present?
      @all_activities = Activity.where("city ILIKE ?", "%#{@trip.destination}%")
      @restaurants = @all_activities.where("category ILIKE ?", "%restaurant%")
      @museums = @all_activities.where(category: 'museum')
      @clubs = @all_activities.where(category: 'club')
      @clubs = @all_activities.where(category: 'club')
      @sights = @all_activities.where(category: 'sight')
      @outdoor = @all_activities.where(category: 'outdoor')
      # @activities = Activity.where("category ILIKE ?", "restaurant")

      # "%#{@activity.category}%"
    # else
    #   @activities = Activity.all
    end
  end

  def show
    @activity_booking = ActivityBooking.find(params[:id])
  end

  def new
    @activity_booking = ActivityBooking.new
    @trip = Trip.find(params[:trip_id])
    @activity_booking.trip = @trip
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @activity_booking = ActivityBooking.new(activity_booking_params)
    @activity_booking.trip = @trip
    # @activity_booking.trip.user = current_user

    if @activity_booking.save!
      redirect_to trip_path(@trip), notice: 'New activity Booking was created successfully!'
    else
      render :new
    end
  end

  def destroy
    @activity_booking = ActivityBooking.find(params[:id])
    @trip = @activity_booking.trip
    @activity_booking.destroy
    redirect_to trip_path(@trip)
  end

  def update
    @activity_booking = ActivityBooking.find(params[:id])
    @activity_booking.update(activity_booking_params)
    @trip = @activity_booking.trip
    redirect_to trip_path(@trip)
  end

  def edit
    @activity_booking = ActivityBooking.find(params[:id])
    @trip = Trip.find(params[:trip_id])
    @activity_booking.trip = @trip
  end

  private

  def activity_booking_params
    params.require(:activity_booking).permit(:booking_date, :people, :activity_id)
  end
end

app/views/activity_bookings/edit.html.erb
<h1 id="add-activity">EDIT AN ACTIVITY</h1>

<%= simple_form_for([@trip, @activity_booking]) do |t| %>
<div class="row">
<div class="form-group col-lg-6">
  <%= t.association :activity, class: 'form-control' %>
</div>
<div class="form-group col-lg-6">
  <%= t.input :people, class: 'form-control' %>
</div>
</div>
<div class="form-group">
  <%= t.input :booking_date, class: 'form-control' %>
</div>
<div class="form-group text-center">
  <%= t.button :submit, class: "btn btn-primary mt-5", id: "button-home-1" %>
</div>
<%= link_to "Delete Reservation" , activity_booking_path(), method: :delete, data: { confirm: "Are you sure?" }%>
<%end%>

app/views/activity_bookings/index.html.erb
<div data-controller="activity-bookings">
  <div class="d-flex mb-5" id="menu-bar">
    <div class="bar-item col-lg-2 completed" id="all-tab" data-activity-bookings-target="allTab groupTab" data-action="click->activity-bookings#revealAll">All</div>
    <div class="bar-item col-lg-2" id="restaurant-tab" data-activity-bookings-target="restaurantTab groupTab" data-action="click->activity-bookings#revealRestaurant">Restaurants</div>
    <div class="bar-item col-lg-2" id="museum-tab" data-activity-bookings-target="museumTab groupTab" data-action="click->activity-bookings#revealMuseum">Museums</div>
    <div class="bar-item col-lg-2" id="club-tab" data-activity-bookings-target="clubTab groupTab" data-action="click->activity-bookings#revealClub">Clubs</div>
    <div class="bar-item col-lg-2" id="sight-tab" data-activity-bookings-target="sightTab groupTab" data-action="click->activity-bookings#revealSight">Sights</div>
    <div class="bar-item col-lg-2" id="outdoor-tab" data-activity-bookings-target="outdoorTab groupTab" data-action="click->activity-bookings#revealOutdoor">Outdoor</div>
  </div>

<div class="activity-index-container" data-activity-bookings-target="restaurant group">
<% @restaurants.each do |activity|%>
  <div class="body_activity_show">
    <div class="container_activity_show">
      <div class="card_activity_show">
        <div class="card-header_activity_show" style="background-image: url(<%= cl_image_path activity.photo.key, height: 300, crop: :lfill %>)">
          </div>
        <div class="card-body_activity_show">
            <span class="tag_activity_show tag-teal_activity_show align-center">
              <%= link_to new_trip_activity_booking_path(@trip, activity_id: activity.id) do %>
                <button class="btn btn-primary" id="button-home-3">Add this activity</button>
            <% end %>
          </span>
          <br>
          <h4><%= activity.name %></h4>
          <h5><%= activity.category.capitalize %></h5>

          <p><%#= activity.description %></p>
          <div class="user_activity_show">
            <div class="user-info_activity_show">
              <h5><%#= activity.category %></h5>
              <h5>Price Class: <%= activity.price_class %>/4</h5>
              <small><%= activity.address %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<div class="activity-index-container" data-activity-bookings-target="museum group">
<% @museums.each do |activity|%>
  <div class="body_activity_show">
    <div class="container_activity_show">
      <div class="card_activity_show">
        <div class="card-header_activity_show" style="background-image: url(<%= cl_image_path activity.photo.key, height: 300, crop: :lfill %>)">
          </div>
        <div class="card-body_activity_show">
            <span class="tag_activity_show tag-teal_activity_show align-center">
              <%= link_to new_trip_activity_booking_path(@trip, activity_id: activity.id) do %>
                <button class="btn btn-primary" id="button-home-3">Add this activity</button>
            <% end %>
          </span>
          <br>
          <h4><%= activity.name %></h4>
          <h5><%= activity.category.capitalize %></h5>

          <p><%#= activity.description %></p>
          <div class="user_activity_show">
            <div class="user-info_activity_show">
              <h5><%#= activity.category %></h5>
              <h5>Price Class: <%= activity.price_class %>/4</h5>
              <small><%= activity.address %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<div class="activity-index-container" data-activity-bookings-target="club group">
<% @clubs.each do |activity|%>
  <div class="body_activity_show">
    <div class="container_activity_show">
      <div class="card_activity_show">
        <div class="card-header_activity_show" style="background-image: url(<%= cl_image_path activity.photo.key, height: 300, crop: :lfill %>)">
          </div>
        <div class="card-body_activity_show">
            <span class="tag_activity_show tag-teal_activity_show align-center">
              <%= link_to new_trip_activity_booking_path(@trip, activity_id: activity.id) do %>
                <button class="btn btn-primary" id="button-home-3">Add this activity</button>
            <% end %>
          </span>
          <br>
          <h4><%= activity.name %></h4>
          <h5><%= activity.category.capitalize %></h5>

          <p><%#= activity.description %></p>
          <div class="user_activity_show">
            <div class="user-info_activity_show">
              <h5><%#= activity.category %></h5>
              <h5>Price Class: <%= activity.price_class %>/4</h5>
              <small><%= activity.address %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<div class="activity-index-container" data-activity-bookings-target="sight group">
<% @sights.each do |activity|%>
  <div class="body_activity_show">
    <div class="container_activity_show">
      <div class="card_activity_show">
          <div class="card-header_activity_show" style="background-image: url(<%= cl_image_path activity.photo.key, height: 300, crop: :lfill %>)">
          </div>
          <%# , height: 500, width: 700, crop: :fill %>
        <div class="card-body_activity_show">
            <span class="tag_activity_show tag-teal_activity_show align-center">
              <%= link_to new_trip_activity_booking_path(@trip, activity_id: activity.id) do %>
                <button class="btn btn-primary" id="button-home-3">Add this activity</button>
            <% end %>
          </span>
          <br>
          <h4><%= activity.name %></h4>
          <h5><%= activity.category.capitalize %></h5>

          <p><%#= activity.description %></p>
          <div class="user_activity_show">
            <div class="user-info_activity_show">
              <h5><%#= activity.category %></h5>
              <h5>Price Class: <%= activity.price_class %>/4</h5>
              <small><%= activity.address %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<div class="activity-index-container" data-activity-bookings-target="outdoor group">
<% @outdoor.each do |activity|%>
  <div class="body_activity_show">
    <div class="container_activity_show">
      <div class="card_activity_show">
        <div class="card-header_activity_show" style="background-image: url(<%= cl_image_path activity.photo.key, height: 250, crop: :fill %>)">
          <%# <%= image_tag activity.photo%>
          <%# , height: 500, width: 700, crop: :fill %>
        </div>
        <div class="card-body_activity_show">
            <span class="tag_activity_show tag-teal_activity_show align-center">
              <%= link_to new_trip_activity_booking_path(@trip, activity_id: activity.id) do %>
                <button class="btn btn-primary" id="button-home-3">Add this activity</button>
            <% end %>
          </span>
          <br>
          <h4><%= activity.name %></h4>
          <h5><%= activity.category.capitalize %></h5>

          <p><%#= activity.description %></p>
          <div class="user_activity_show">
            <div class="user-info_activity_show">
              <h5><%#= activity.category %></h5>
              <h5>Price Class: <%= activity.price_class %>/4</h5>
              <small><%= activity.address %></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/activity_bookings/new.html.erb
<%= form_for([@trip, @activity_booking]) do |t| %>
<div class="d-none">
<%= t.text_field :activity_id, value: params[:activity_id], as: :hidden %>
</div>
<div class="label text-center" id="ab-1">
    <%= t.label :Confirm_your_activity_booking %>
  </div>
<div class="d-flex row">
    <%= t.number_field :people, class: 'form-control col-lg-6', min: 1, placeholder: 'How many people?' %>
    <%= t.datetime_field :booking_date, class: 'form-control col-lg-6', id: 'timeframe', placeholder: 'Check-in date' %>
</div>
<div class="form-group text-center">
  <%= t.button :submit, class: "btn btn-primary mt-5", id: "button-home-3" %>
</div>
<%end%>

app/views/activity_bookings/show.html.erb
<div class="background-show d-flex justify-content-center">
  <div class="background_show_activity">
    <div class="background_show_activity_two">
      <div class="text-left">
        <%= link_to "BACK", trip_path(@activity_booking.trip), class: "btn btn-primary", id:"button-left-2" %>
      </div>
      <%# <p><%= @activity_booking.trip</p> %>
      <h3 class="text-center"><%= @activity_booking.activity.name %></h3>
      <h4><b>Category</b></h4>
      <p><%= @activity_booking.activity.category.capitalize %></p>
      <h4><b>Description</b></h4>
      <p><%= @activity_booking.activity.description %></p>
      <h4><b>Adress</b></h4>
      <p> <%= @activity_booking.activity.address %></p>
      <h4><b>Price Class</b></h4>
      <p><%= @activity_booking.activity.price_class %></p>

      <h4><b>Booking Date</b></h4>
      <p><%= @activity_booking.booking_date.strftime("%A, %b %d") %></p>
      <h4><b>Number of People</b></h4>
      <p><%= @activity_booking.people %></p>
      <%# <p><%= @activity_booking.status</p> %>
    </div>
  </div>
</div>