config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # root to: 'pages#team'
  get "/pages/:page" => "pages#show"
  get "/pages/team" => "pages#team"
  resources :trips do
    resources :activity_bookings, only: [:index, :new, :create, :update, :edit, :show ]
    resources :hotel_bookings, only: [:index, :new, :create, :update, :edit, :show ]
  end
  resources :activity_bookings, only: [ :destroy ]
  resources :hotel_bookings, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="footer_border"></div>

<footer class="page-footer font-small">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h4 class="font-weight-bold text-uppercase mt-3 mb-4">About</h4>

        <ul class="list-unstyled">
          <li class="Link">
            <a href="#!">LeConcierge LuxeEdition</a>
          </li>
          <li class="Link">
            <a href="#!">LeConcierge Awards</a>
          </li>
          <li class="Link">
            <a href="#!">About us</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h4 class="font-weight-bold text-uppercase mt-3 mb-4">Community</h4>

        <ul class="list-unstyled">
          <li class="Link">
            <a href="#!">Dickpics Louis Labes</a>
          </li>
          <li class="Link">
            <a href="#!">LeDate</a>
          </li>
          <li class="Link">
            <a href="#!">LeFuck</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h4 class="font-weight-bold text-uppercase mt-3 mb-4">Host</h4>

        <ul class="list-unstyled">
          <li class="Link">
            <a href="#!">Community Center</a>
          </li>
          <li class="Link">
            <a href="#!">Service Center</a>
          </li>
          <li class="Link">
            <a href="#!">Ariana Grande Nudes</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h4 class="font-weight-bold text-uppercase mt-3 mb-4">Support</h4>

        <ul class="list-unstyled">
          <li class="Link">
            <a href="#!">Arbeitsamt</a>
          </li>
          <li  class="Link">
            <a href="#!">Shiqptar Mafia</a>
          </li>
          <li  class="Link">
            <a href="#!">Frank Rosin</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <!-- Copyright -->

</footer>
  <div class="footer-copyright text-center py-3">© 2021 Copyright:
    <a href="https://LeConciergeINC.com">LeConciergeINC.com</a>
  </div>
<!-- Footer -->
</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-lights p-3">
  <div class="navbar-brand anti_link">
    <%= link_to 'LE CONCIERGE', root_path, id: "le-concierge"  %>
    <i class="fas fa-concierge-bell" style="font-size:30px;" id="navbar_concierge_bell"></i>
  </div>
  <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link anti_link mr-3" href="#">About us<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a href=""><%= link_to "Our Team", pages_team_path, class: "nav-link anti_link mr-3" %></a>
      </li>
    </ul>


    <% if user_signed_in? %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item anti_link mr-3">
        <%= link_to 'ALL TRIPS', trips_path, class: "nav-item"  %>
      </li>
      <li class="nav-item anti_link mr-3">
        <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "nav-item" %>
      </li>
    </ul>
    <% else %>
     <ul class="navbar-nav ml-auto">
      <li class="nav-item anti_link mr-3">
        <%= link_to "LOGIN", new_user_session_path, class: "nav-item" %>
      </li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeConcierge makes travelling simple, comfortable and extraordinary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cambo&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cambo&family=Lato:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <meta name="description" content="LeConcierge takes care of your entire trip. Fill your stay with Accommoadtions, Restaurants, Clubs, Sights, Cultural Acitivities and many more. Confirm your booking for all activities with just ONE click.">
    <meta name="keywords" content="city, interatcive, travelling, travel, trip, vacation, booking, trivago, luxury, special, planning, restaurant, hotel, accommodation, sights, museum, party, weekend, brunch">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>